-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 12:00:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `cod_autor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `livro_cod_livro` INT NOT NULL,
  PRIMARY KEY (`cod_autor`, `livro_cod_livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `cod_genero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `cod_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `preço` DOUBLE(6,2) NOT NULL,
  `saldo` INT NULL,
  `genero_cod_genero` INT NOT NULL,
  PRIMARY KEY (`cod_livro`, `genero_cod_genero`),
  INDEX `fk_livro_genero1_idx` (`genero_cod_genero` ASC) VISIBLE,
  CONSTRAINT `fk_livro_genero1`
    FOREIGN KEY (`genero_cod_genero`)
    REFERENCES `mydb`.`genero` (`cod_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `cod_venda` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `vl_total` DECIMAL(6,2) NOT NULL,
  `cliente_cod_cliente` INT NOT NULL,
  PRIMARY KEY (`cod_venda`, `cliente_cod_cliente`),
  INDEX `fk_venda_cliente1_idx` (`cliente_cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_cod_cliente`)
    REFERENCES `mydb`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`livro_autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`livro_autor` (
  `autor_cod_autor` INT NOT NULL,
  `autor_livro_cod_livro` INT NOT NULL,
  `livro_cod_livro` INT NOT NULL,
  PRIMARY KEY (`autor_cod_autor`, `autor_livro_cod_livro`, `livro_cod_livro`),
  INDEX `fk_livro_autor_livro1_idx` (`livro_cod_livro` ASC) VISIBLE,
  CONSTRAINT `fk_livro_autor_autor`
    FOREIGN KEY (`autor_cod_autor` , `autor_livro_cod_livro`)
    REFERENCES `mydb`.`autor` (`cod_autor` , `livro_cod_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_autor_livro1`
    FOREIGN KEY (`livro_cod_livro`)
    REFERENCES `mydb`.`livro` (`cod_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda_livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda_livro` (
  `Qtde` INT NOT NULL AUTO_INCREMENT,
  `vl_sub_total` DOUBLE(6,2) NOT NULL,
  `livro_cod_livro` INT NOT NULL,
  `venda_cod_venda` INT NOT NULL,
  PRIMARY KEY (`Qtde`, `vl_sub_total`, `livro_cod_livro`, `venda_cod_venda`),
  INDEX `fk_venda_livro_livro1_idx` (`livro_cod_livro` ASC) VISIBLE,
  INDEX `fk_venda_livro_venda1_idx` (`venda_cod_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_livro_livro1`
    FOREIGN KEY (`livro_cod_livro`)
    REFERENCES `mydb`.`livro` (`cod_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_livro_venda1`
    FOREIGN KEY (`venda_cod_venda`)
    REFERENCES `mydb`.`venda` (`cod_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
